# Generated by Django 5.1.6 on 2026-01-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Charity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("logo", models.URLField(blank=True)),
                ("website", models.URLField()),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        help_text="CHY number for Irish charities",
                        max_length=50,
                    ),
                ),
                ("registration_country", models.CharField(default="IE", max_length=2)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("children", "Children"),
                            ("health", "Health"),
                            ("animals", "Animals"),
                            ("environment", "Environment"),
                            ("international", "International"),
                            ("homelessness", "Homelessness"),
                            ("mental_health", "Mental Health"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Charities",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["slug"], name="charities_c_slug_a429d8_idx"),
                    models.Index(
                        fields=["category", "is_active"],
                        name="charities_c_categor_e011c2_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="charities_c_is_acti_207d3c_idx"
                    ),
                    models.Index(
                        fields=["is_verified", "is_active"],
                        name="charities_c_is_veri_d1fdb0_idx",
                    ),
                ],
            },
        ),
    ]
