# Generated by Django 5.1.6 on 2026-01-16 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("charities", "0001_initial"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("donor_name", models.CharField(max_length=200)),
                ("donor_email", models.EmailField(max_length=254)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("message", models.TextField(blank=True)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("stripe_session_id", models.CharField(blank=True, max_length=200)),
                ("stripe_payment_intent", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "charity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to="charities.charity",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "status"],
                        name="donations_d_event_i_dd159d_idx",
                    ),
                    models.Index(
                        fields=["charity", "status"],
                        name="donations_d_charity_bebc87_idx",
                    ),
                    models.Index(
                        fields=["status"], name="donations_d_status_73ca83_idx"
                    ),
                    models.Index(
                        fields=["stripe_session_id"],
                        name="donations_d_stripe__f6d640_idx",
                    ),
                    models.Index(
                        fields=["stripe_payment_intent"],
                        name="donations_d_stripe__65d140_idx",
                    ),
                    models.Index(
                        fields=["donor_email"], name="donations_d_donor_e_914ea9_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="donations_d_created_7012d0_idx"
                    ),
                ],
            },
        ),
    ]
